<a href="https://colab.research.google.com/github/sb0611sb/2026BDA/blob/main/w06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np

In [3]:
!git clone https://github.com/ai7dnn/2026-1-BDA

Cloning into '2026-1-BDA'...
remote: Enumerating objects: 311, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 311 (delta 55), reused 10 (delta 10), pack-reused 228 (from 2)
Receiving objects: 100% (311/311), 50.25 MiB | 29.27 MiB/s, done.
Resolving deltas: 100% (161/161), done.

In [54]:
df = pd.read_csv('/content/2026-1-BDA/2016년졸음운전.csv', encoding='euc-kr', index_col=0)

In [22]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [23]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [25]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [26]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [27]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [28]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [29]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [30]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [31]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [32]:
df.max(axis=None)

522

In [33]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [34]:
df.iloc[:,1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [36]:
df2 = df.copy()

df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364
총계         2433     98   4899

In [37]:
df2[df2 > 10]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    NaN    387
2016년2월     174    NaN    328
2016년3월     217    NaN    435
2016년4월     216    NaN    419
2016년5월     239   13.0    522
2016년6월     200   12.0    362
2016년7월     227    NaN    460
2016년8월     230    NaN    490
2016년9월     187   13.0    347
2016년10월    183    NaN    367
2016년11월    200    NaN    418
2016년12월    168    NaN    364
총계         2433   98.0   4899

In [41]:
df2['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
총계          False
Name: 사망(명), dtype: bool

In [42]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [44]:
df3 = df.copy()
df3[df3>10] =-df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [45]:
dfn = pd.DataFrame({'A':range(1,6),
                   'B': range(6,-3,-2),
                   'C':range(10,5,-1),
                   'D clmns':range(3,-2,-1),
                   'E':['python','java','python','go','python']})

In [46]:
dfn.query('A>B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [47]:
dfn.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [48]:
dfn.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [49]:
num = 3
dfn.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [50]:
dfn.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [51]:
df.sort_index()

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [52]:
df.sort_index(ascending=False)

   A  B   C  D clmns       E
4  5 -2   6       -1  python
3  4  0   7        0      go
2  3  2   8        1  python
1  2  4   9        2    java
0  1  6  10        3  python

In [55]:
df.sort_values(by='사망(명)')

          사고(건)  사망(명)  부상(명)
연월
2016년12월    168      4    364
2016년1월     192      5    387
2016년11월    200      5    418
2016년2월     174      6    328
2016년8월     230      7    490
2016년4월     216      7    419
2016년3월     217      7    435
2016년7월     227      9    460
2016년10월    183     10    367
2016년6월     200     12    362
2016년5월     239     13    522
2016년9월     187     13    347

In [59]:
df.sort_values(by=['2016년12월'],axis=1, ascending=False)

          부상(명)  사고(건)  사망(명)
연월
2016년1월     387    192      5
2016년2월     328    174      6
2016년3월     435    217      7
2016년4월     419    216      7
2016년5월     522    239     13
2016년6월     362    200     12
2016년7월     460    227      9
2016년8월     490    230      7
2016년9월     347    187     13
2016년10월    367    183     10
2016년11월    418    200      5
2016년12월    364    168      4

In [60]:
dates=pd.date_range('20260101', periods=6)
dfm=pd.DataFrame(np.arange(24).reshape(6,4), index=dates)
dfm

             0   1   2   3
2026-01-01   0   1   2   3
2026-01-02   4   5   6   7
2026-01-03   8   9  10  11
2026-01-04  12  13  14  15
2026-01-05  16  17  18  19
2026-01-06  20  21  22  23

In [62]:
dfm.columns = list('ABCD')
dfm

             A   B   C   D
2026-01-01   0   1   2   3
2026-01-02   4   5   6   7
2026-01-03   8   9  10  11
2026-01-04  12  13  14  15
2026-01-05  16  17  18  19
2026-01-06  20  21  22  23

In [63]:
s1 = pd.Series([1,2,3,4,5], index=pd.date_range('20260101', periods=5))
s1

2026-01-01    1
2026-01-02    2
2026-01-03    3
2026-01-04    4
2026-01-05    5
Freq: D, dtype: int64

In [65]:
dfm['E'] = s1
dfm

             A   B   C   D    E
2026-01-01   0   1   2   3  1.0
2026-01-02   4   5   6   7  2.0
2026-01-03   8   9  10  11  3.0
2026-01-04  12  13  14  15  4.0
2026-01-05  16  17  18  19  5.0
2026-01-06  20  21  22  23  NaN

In [66]:
dfm.loc['2026-01-01','A'] = 10
dfm

             A   B   C   D    E
2026-01-01  10   1   2   3  1.0
2026-01-02   4   5   6   7  2.0
2026-01-03   8   9  10  11  3.0
2026-01-04  12  13  14  15  4.0
2026-01-05  16  17  18  19  5.0
2026-01-06  20  21  22  23  NaN

In [70]:
dfm.at[dates[2],df.columns[2]] = 100
dfm

             A   B   C   D    E  부상(명)
2026-01-01  10   1   2   3  1.0    NaN
2026-01-02   4   5  60   7  2.0    NaN
2026-01-03   8   9  10  11  3.0  100.0
2026-01-04  12  13  14  15  4.0    NaN
2026-01-05  16  17  18  19  5.0    NaN
2026-01-06  20  21  22  23  NaN    NaN

In [71]:
dfm.iloc[1,2] =60
dfm

             A   B   C   D    E  부상(명)
2026-01-01  10   1   2   3  1.0    NaN
2026-01-02   4   5  60   7  2.0    NaN
2026-01-03   8   9  10  11  3.0  100.0
2026-01-04  12  13  14  15  4.0    NaN
2026-01-05  16  17  18  19  5.0    NaN
2026-01-06  20  21  22  23  NaN    NaN

In [72]:
dates = pd.date_range('20260101', periods=7,freq='W-MON')
dfn = pd.DataFrame(np.arange(35).reshape(7,5),index=dates,columns=list('ABCDE'))
subdates = pd.date_range('20260106', periods=5, freq='W-MON')
s = pd.Series(np.linspace(10,17,5), index=subdates)
s

2026-01-12    10.00
2026-01-19    11.75
2026-01-26    13.50
2026-02-02    15.25
2026-02-09    17.00
Freq: W-MON, dtype: float64

In [73]:
dfn['F'] = s
dfn

             A   B   C   D   E      F
2026-01-05   0   1   2   3   4    NaN
2026-01-12   5   6   7   8   9  10.00
2026-01-19  10  11  12  13  14  11.75
2026-01-26  15  16  17  18  19  13.50
2026-02-02  20  21  22  23  24  15.25
2026-02-09  25  26  27  28  29  17.00
2026-02-16  30  31  32  33  34    NaN

In [74]:
dfn2 =dfn.copy()
dfn2.iloc[3,4]=np.nan
dfn2.iloc[1,:]=np.nan
dfn2

               A     B     C     D     E      F
2026-01-05   0.0   1.0   2.0   3.0   4.0    NaN
2026-01-12   NaN   NaN   NaN   NaN   NaN    NaN
2026-01-19  10.0  11.0  12.0  13.0  14.0  11.75
2026-01-26  15.0  16.0  17.0  18.0   NaN  13.50
2026-02-02  20.0  21.0  22.0  23.0  24.0  15.25
2026-02-09  25.0  26.0  27.0  28.0  29.0  17.00
2026-02-16  30.0  31.0  32.0  33.0  34.0    NaN

In [75]:
dfn2.isnull()

                A      B      C      D      E      F
2026-01-05  False  False  False  False  False   True
2026-01-12   True   True   True   True   True   True
2026-01-19  False  False  False  False  False  False
2026-01-26  False  False  False  False   True  False
2026-02-02  False  False  False  False  False  False
2026-02-09  False  False  False  False  False  False
2026-02-16  False  False  False  False  False   True

In [78]:
dfn2.count()

A    6
B    6
C    6
D    6
E    5
F    4
dtype: int64

In [77]:
dfn2.count(axis=1)

2026-01-05    5
2026-01-12    0
2026-01-19    6
2026-01-26    5
2026-02-02    6
2026-02-09    6
2026-02-16    5
Freq: W-MON, dtype: int64

In [80]:
s=dfn2.E.value_counts()
s

E
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [82]:
s=dfn2.E.value_counts(dropna=False)
s

E
NaN     2
4.0     1
14.0    1
24.0    1
29.0    1
34.0    1
Name: count, dtype: int64

In [81]:
dfn2['D'].value_counts().to_frame()

      count
D
3.0       1
13.0      1
18.0      1
23.0      1
28.0      1
33.0      1

In [83]:
dfn2.dropna()

               A     B     C     D     E      F
2026-01-19  10.0  11.0  12.0  13.0  14.0  11.75
2026-02-02  20.0  21.0  22.0  23.0  24.0  15.25
2026-02-09  25.0  26.0  27.0  28.0  29.0  17.00

In [84]:
dfn2.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [2026-01-05 00:00:00, 2026-01-12 00:00:00, 2026-01-19 00:00:00, 2026-01-26 00:00:00, 2026-02-02 00:00:00, 2026-02-09 00:00:00, 2026-02-16 00:00:00]

In [85]:
dfn2[dfn2.isnull()]=500
dfn2

                A      B      C      D      E       F
2026-01-05    0.0    1.0    2.0    3.0    4.0  500.00
2026-01-12  500.0  500.0  500.0  500.0  500.0  500.00
2026-01-19   10.0   11.0   12.0   13.0   14.0   11.75
2026-01-26   15.0   16.0   17.0   18.0  500.0   13.50
2026-02-02   20.0   21.0   22.0   23.0   24.0   15.25
2026-02-09   25.0   26.0   27.0   28.0   29.0   17.00
2026-02-16   30.0   31.0   32.0   33.0   34.0  500.00

In [87]:
dfn = pd.DataFrame([[np.nan,2,np.nan,0],
                   [3,4,np.nan,1],
                   [np.nan,np.nan,np.nan,np.nan],
                   [np.nan,3,np.nan,4]],
                   columns=list('ABCD'))

In [88]:
dfn.fillna(10)

      A     B     C     D
0  10.0   2.0  10.0   0.0
1   3.0   4.0  10.0   1.0
2  10.0  10.0  10.0  10.0
3  10.0   3.0  10.0   4.0

In [89]:
dfn.fillna('missing',limit=1,axis=1)

         A    B        C    D
0  missing  2.0      NaN  0.0
1      3.0  4.0  missing  1.0
2  missing  NaN      NaN  NaN
3  missing  3.0      NaN  4.0

In [91]:
dfn.fillna('value',axis=1)

       A      B      C      D
0  value    2.0  value    0.0
1    3.0    4.0  value    1.0
2  value  value  value  value
3  value    3.0  value    4.0

In [93]:
s= pd.DataFrame([100,200,400], index=list('ADC'))

dfn.fillna(value=s,limit=1)

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [94]:
dfn.fillna(method='ffill')

/tmp/ipykernel_4235/2695030350.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfn.fillna(method='ffill')

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  3.0  4.0 NaN  1.0
3  3.0  3.0 NaN  4.0

In [96]:
dfn.fillna(df.mean())

     A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [104]:
dfn.fillna(dfn.mean()['D'],limit=1)

          A         B         C         D
0  1.666667  2.000000  1.666667  0.000000
1  3.000000  4.000000       NaN  1.000000
2       NaN  1.666667       NaN  1.666667
3       NaN  3.000000       NaN  4.000000